apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hashicorp-ovh-provider.fullname" . }}-config
  labels:
    {{- include "hashicorp-ovh-provider.labels" . | nindent 4 }}
type: Opaque
data:
  ovh-application-key: {{ .Values.config.ovh.applicationKey | b64enc | quote }}
  ovh-application-secret: {{ .Values.config.ovh.applicationSecret | b64enc | quote }}
  ovh-consumer-key: {{ .Values.config.ovh.consumerKey | b64enc | quote }}
